const userMock = {
  codigo:
    'eyJhbGciOiJSUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOjEwMTI0OTQsImFkbWluIjpmYWxzZSwiaWF0IjoxNjE2NzY1MTQ2LCJleHAiOjE2MTY3Nzk1NDYsImF1ZCI6Imh0dHBzOi8vcGVibWVkLmNvbS5iciIsImlzcyI6IlBFQk1FRCIsInN1YiI6Im1hcmNlbG8udHJhdmFzc29AcGVibWVkLmNvbS5iciJ9.NM6fUIJnyzRIzQYAaVuOAUsCBRqyWz1-p4ORKb3DxQ7_-FPSmkAotECyJ-aPCBAgLdTj5gJL0GUY7Li_-Y3BgQ',
  usuario: {
    id: 999999,
    perfil_usuario: 4,
    perfis_usuario: [
      {
        perfil: 'geral',
        id_perfil: 1,
        ativo: 1,
      },
      {
        perfil: 'estudante_saude_nao_medicina',
        id_perfil: 4,
        ativo: 1,
      },
    ],
    nome: 'User',
    sobrenome: 'Mock',
    nome_completo: 'User Mock',
    email: 'user.mock@pebmed.com.br',
    email_status: 1,
    nascimento: '1995-10-12T00:00:00.000Z',
    graduacao: null,
    id_universidade: null,
    id_especialidade: null,
    especialidade: null,
    id_tipo_usuario: 2,
    data_cadastro: '2021-03-16T17:12:15.000Z',
    cpf: '61073489051',
    grau_formacao: 'estudante',
    num_conselho_profis: null,
    id_formacao_medica: null,
    id_formacao: null,
    id_area_atuacao: 76,
    area_atuacao: 'Outros Profissionais de Saúde',
    telefone: '21999999999',
    id_pais_nacionalidade: 33,
    app_codigo: 'NURSEBOOK',
    id_facebook: null,
    endereco: {
      id: 922047,
      id_usuario: 1012494,
      logradouro: null,
      comp: null,
      bairro: null,
      cidade: null,
      uf: 'RJ',
      id_pais: 33,
      numero: null,
      cep: null,
    },
    codigo_aprovacao: null,
    crm_verificado: false,
    data_verificacao_crm: null,
    solicitar_atualizacao: 0,
    ativo: 1,
    lastActivityReason: null,
    ultimo_produto_utilizado: 'NURSEBOOK',
  },
};

export default userMock;
